sillsdev/StoryProducer

app/build.gradle
app/google-services.json
app/src/main/java/org/sil/storyproducer/controller/MultiRecordFrag.kt
app/src/main/java/org/sil/storyproducer/controller/RegistrationActivity.kt
app/src/main/java/org/sil/storyproducer/controller/dramatization/DramatizationRecordingToolbar.kt
app/src/main/java/org/sil/storyproducer/controller/phase/PhaseBaseActivity.kt
app/src/main/java/org/sil/storyproducer/model/Registration.kt
app/src/main/java/org/sil/storyproducer/model/StoryIO.kt
app/src/main/java/org/sil/storyproducer/tools/file/AudioFiles.kt
app/src/main/java/org/sil/storyproducer/tools/file/FileIO.kt
app/src/main/java/org/sil/storyproducer/tools/media/AudioRecorder.kt
app/src/main/java/org/sil/storyproducer/tools/media/story/AutoStoryMaker.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

Issue #505 - Updated Firebase SDK

---

app/src/main/java/org/sil/storyproducer/model/Slide.kt
app/src/main/java/org/sil/storyproducer/model/Story.kt
app/src/main/java/org/sil/storyproducer/model/StoryIO.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/java/org/sil/storyproducer/viewmodel/SlideViewModelBuilder.kt
app/src/main/res/values/strings.xml

Fix sillsdev/StoryProducer#532 with accepting older templates with LOCALCREDITS slides.

Issue#532 Accept older templates with LOCALCREDITS slides

---

app/src/main/java/org/sil/storyproducer/activity/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/activity/WorkspaceDialogUpdateActivity.kt
app/src/main/res/layout/dialog_welcome_screen.xml
app/src/main/res/values/strings.xml

- removes button to add demo to workspace
- formats welcome message
- updates dialog for choosing template folder from welcome screen and main menu

Issue #541 - Revise Welcome Screen

---

app/build.gradle
app/src/main/java/org/sil/storyproducer/controller/wordlink/WordLinksActivity.kt

In the SDK Manager in Android Studio, Android 11 (API 30) needs to be installed.

update to sdk 30

---

app/src/main/java/org/sil/storyproducer/tools/media/pipe/PipedVideoSurfaceEncoder.kt

Per Issue #639, update software to eliminate "FrameEvents: updateAcquireFence: Did not find frame" error.
With the advent of Android 11 and later versions, the Codec encoder began reporting to the system error log the following error per frame of data:
**
> FrameEvents: updateAcquireFence: Did not find frame.
**
For small stories (6 slides), this resulted ~3000 error messages to the system log.  Further analysis of the performance data showed that in most cases, the software codec encoder performed better than the hardware encoder.
**This was tested the following devices:**
Pixel 5 Android 12
Samsung Android 10
Samsung Android 9
Android Studio Pixel 5 emulator for Android 12 & Android 11

SP639-Fix 'FrameEvents: updateAcquireFence: Did not find frame' error

---

app/src/main/java/org/sil/storyproducer/controller/MultiRecordFrag.kt
app/src/main/java/org/sil/storyproducer/model/Slide.kt
app/src/main/java/org/sil/storyproducer/tools/media/story/AutoStoryMaker.kt
app/src/main/java/org/sil/storyproducer/viewmodel/SlideViewModelBuilder.kt
app/src/main/res/drawable/baseline_restore_page_24_white.xml
app/src/main/res/layout/fragment_slide.xml
app/src/main/res/values/strings.xml

SP422- Swap Images via camera tool

---

app/src/main/java/org/sil/storyproducer/activities/WelcomeDialogActivity.kt
app/src/main/java/org/sil/storyproducer/controller/StoryListFrag.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/StoryPageFragment.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/res/layout/dialog_about.xml
app/src/main/res/layout/dialog_welcome_screen.xml
app/src/main/res/layout/fragment_no_stories.xml
app/src/main/res/menu/drawer_view.xml
app/src/main/res/values/global_menu_array.xml
app/src/main/res/values/strings.xml

Peter, I'd appreciate your review of the PR.

Getting Started UX for v3.2

---

app/src/test/java/org/sil/storyproducer/model/StoryTest.kt

This PR introduces a unit test file for `Story` and tests the `shortTitle` method.

Add StoryTest with test for shortTitle

---

app/src/main/java/org/sil/storyproducer/model/BLBookList.kt

AWS complete SP bloom catalog download with samples fallback

Read full BL catalog

---

app/src/main/java/org/sil/storyproducer/model/BLBookList.kt

Other warnings are due to deprecated AsyncTask functions

Fixed some BLBookList.kt warnings

---

app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/activities/WelcomeDialogActivity.kt

Bug #802 is fixed in this pull request

Fixed (notion.so) bug #802 - Welcome, Select Folder, Cancel then hang

---

app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/BaseController.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/SelectTemplatesFolderController.kt
app/src/main/java/org/sil/storyproducer/controller/export/ExportedVideosAdapter.kt
app/src/main/java/org/sil/storyproducer/model/ParseBloom.kt
app/src/main/java/org/sil/storyproducer/model/ParsePhotoStory.kt
app/src/main/java/org/sil/storyproducer/model/StoryIO.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/java/org/sil/storyproducer/tools/Utilities.kt
app/src/main/java/org/sil/storyproducer/tools/file/FileIO.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/file_paths.xml
app/src/test/java/org/sil/storyproducer/controller/SelectTemplatesFolderControllerTest.kt

The two commits in this PR are squashed from the 15 commits in Peter's ithinkapps branch and pull request #688

Automatic storage feature

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/bldownload/BLDownloadActivity.kt
app/src/main/java/org/sil/storyproducer/controller/wordlink/WordLinksListActivity.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/java/org/sil/storyproducer/tools/media/story/AutoStoryMaker.kt
app/src/main/res/menu/drawer_view.xml
app/src/main/res/values/global_menu_array.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

Squashed and refactored Peter's pull request 703 commits just a bit

121 settings plus other fixes

---

app/src/androidTest/java/org/sil/storyproducer/androidtest/happypath/PhaseTestBase.kt
app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/SplashScreenActivity.kt
app/src/main/java/org/sil/storyproducer/controller/phase/PhaseBaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/wordlink/WordLinksListActivity.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/java/org/sil/storyproducer/view/BaseActivityView.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_wordlink_list.xml
app/src/main/res/layout/phase_frame.xml

Unify all hamburger menus to use same style

---

app/src/main/res/values/strings.xml

Task 139: UI - update to use “Story List”

Task 139: UI - update to use “Story List”

---

app/src/main/java/org/sil/storyproducer/model/BloomFrontCoverSlideBuilder.kt

Bug 836 Fixed white space in localized title name obtained from .htm parsing

---

app/src/main/java/org/sil/storyproducer/controller/translaterevise/TranslateReviseFrag.kt
app/src/main/java/org/sil/storyproducer/viewmodel/SlideViewModelBuilder.kt

Bugfixes 836b story list problem2 + Popup Help song side re-showing

---

app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/PopupHelpUtils.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

Two commits that you can keep as separate.

Feature/balloon help round corners + WordLinks enable setting

---

app/src/main/java/org/sil/storyproducer/controller/MultiRecordFrag.kt
app/src/main/res/drawable/baseline_restore_page_24_white.xml

Bug 838: Replacing an slide image with a photo (partial fix, now rotated)

---

app/src/main/java/org/sil/storyproducer/controller/MultiRecordFrag.kt

Bug 838: Replacing a slide image with a photo (possible fix)

---

app/src/main/java/org/sil/storyproducer/controller/accuracycheck/AccuracyCheckFrag.kt
app/src/main/res/drawable/outlined_button_background.xml
app/src/main/res/drawable/outlined_button_inset.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Added affirmation dialog outlined buttons as requested

Task 147 - Outlined Buttons in Affirmation dialog

---

app/src/main/java/org/sil/storyproducer/tools/media/AudioRecorder.kt
app/src/main/res/values/strings.xml

Bugfix 840: Double-tap recording error

---

app/src/main/java/org/sil/storyproducer/model/BLBookList.kt
app/src/main/java/org/sil/storyproducer/model/StoryIO.kt

For updating thumbnails after a story list update.

Added check for latest Bible Story Template thumbnail timestamp

---

app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/PopupHelpUtils.kt
app/src/main/java/org/sil/storyproducer/controller/accuracycheck/AccuracyCheckFrag.kt
app/src/main/java/org/sil/storyproducer/controller/communitywork/CommunityWorkFrag.kt
app/src/main/java/org/sil/storyproducer/controller/export/FinalizeActivity.kt
app/src/main/java/org/sil/storyproducer/controller/export/ShareActivity.kt
app/src/main/java/org/sil/storyproducer/controller/learn/LearnActivity.kt
app/src/main/java/org/sil/storyproducer/controller/translaterevise/TranslateReviseFrag.kt
app/src/main/java/org/sil/storyproducer/controller/voicestudio/VoiceStudioFrag.kt
app/src/main/res/drawable-anydpi/ic_action_video_full.xml
app/src/main/res/drawable-anydpi/ic_action_video_full_exit.xml
app/src/main/res/layout/animated_message_x.xml
app/src/main/res/values/dimens.xml

Feature - Added fullscreen and exit-fullscreen actions on training vids

---

app/src/main/java/org/sil/storyproducer/controller/PopupHelpUtils.kt

A minor code fix for the wrong video scaling phase 1-7

Bugfix - Wrong html5 animation scaling for phase 1-7 videos
