sillsdev/StoryProducer

.gitignore
.travis.yml
README.md
app/build.gradle
gradle.properties

* Disable jetifier for kotlin compiler (broke on TeamCity)
* Conditionally sign APK
* Include instructions in README.md for creating signed APK
* change versionName back to '3.0.2'
* when signing, include versionName in the APK outputFileName

Implement continuous integration via TeamCity and Travis

---

app/src/main/res/values/strings.xml

Issue #517. This adds a new line to the beginning of the local credits saying: "Local Contact (phone/email):". Here is an example of the new change.
This has been tested with the other local credit changes made in #419.

Issue #517 - Add Local Contact to the Local Credits

---

app/src/main/java/org/sil/storyproducer/controller/phase/PhaseBaseActivity.kt

Prevent Story Producer from saving a story that doesn't belong in the workspace. Ensures that the story exists in the workspace before trying to save it.
Steps to reproduce: (from #503)
- Prepare SD card with two SP Template folders:
- ‘SP Templates A’ with .bloom templates 001 and 002
- ‘SP Templates B’ with .bloom templates 006 and 007
- Run SP 3.0.2
- Select folder ‘SP Templates A’
- Open story 001. Go to Translation phase.
- With story 001 still open, do Menu > Select SP Templates folder and select SP Templates B.
- Unexpectedly, SP writes a new a lone rogue story.json file in a new rogue folder:
- SP Templates B / 001 Widow’s Gift / project
- This file and folder should not be written.

Issue #503 - Rouge Story File

---

app/src/main/java/org/sil/storyproducer/activity/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt

#539 
When switching to a workspace SP was somehow holding onto previous information during the transformation process. This change fixes that by resetting the Story information to an empty story before switching the workspace over.
Testing Steps
- Clean Directory
- Add story 001.bloom
- Open SP 3.0.3 and start story
- Leave SP open (at the Story Templates list e.g.)
- Use file manager to add 002.bloom to the same directory as story 001
- In SP, do "Select SP Templates folder" to rescan the directory

Issue #539 - Template Corruption

---

app/src/main/java/org/sil/storyproducer/model/Registration.kt
app/src/main/java/org/sil/storyproducer/tools/file/FileIO.kt

Problem:  Users would lose all their data after the Accuracy Check phase if they exited Story Producer on an Android 10 & 11 platform.
Solution: Between phases, the story.json file is opened and then written.  story.json was not truncated on the open, but over written with the new data.  If the new data was smaller than the previous data in the file, garbage characters from the old data would be left in the file.  This changes opens story.json in truncate mode which deletes all the old data in the file and ensures that only the new data is written to the file.
Test:  Tested fix on Pixel 2/Android 9 and Pixel 5/Android 11.

Fix data loss problem for Android 10 & 11 (#549)

---

app/src/main/java/org/sil/storyproducer/service/SlideService.kt
app/src/main/java/org/sil/storyproducer/tools/file/FileIO.kt

Problem: During finalize state on an Android 11/Pixel 5 configuration, Story Producer would crash when trying to create a Story that contained a video.
Solution:  The problem was traced to not catching an exception for call "iStream.available()" in SlideService.kt and FileIO.kt.   iStream is an input stream that was opened on a file named "" (empty string).  For Android 11, iStream.available() throws an exception.  For previous versions of Android it returns a 0.

Fix for #548 Android 11 SP crash in finalize; no video produced

---

app/src/main/res/values/strings.xml

Only the local option is currently available, so the 'remote' option remains commented out until implemented!

Remove the 'Remote' item option from the location type in registration

---

app/src/main/java/org/sil/storyproducer/controller/RegistrationActivity.kt

Problem: Data saved during registration is not persisted when registration data is updated
Solution: Introduction of a different package name in the google-services.json for continuous builds caused a error when parsing the registration.json file.  The RegistrationActivity.kt file was updated to account for the new package name.

Issue #559: Fix for Registration Data Loss in CI Build

---

app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/BaseController.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/java/org/sil/storyproducer/view/BaseActivityView.kt

Problem: SP hangs on Registration Submit
Solution:  Problem was traced to terminating the MainActivity before calling the RegistrationActivity.  The submit button on the RegistrationActivity forces Story Producer to the background for the submission of the data via another APP. When the Story Producer APP becomes active, the MainActivity is not around to orchestrate story production.
Testing: Ran through several scenarios of registration submissions for Android 11 on a Pixel 5 and Android 8.1 on a Pixel 3.

Issue #573: SP hangs on Registration Submit

---

app/src/main/java/org/sil/storyproducer/model/StoryIO.kt

Report Story Parse Exceptions and Handle them appropriately.
**Solution**: Log a message and an exception to Firebase when this happens.  Also, log a message to the Android system log file.  This message to the Andorid system log is similar to the one posted to Firebase but can be viewed immediately with the Android Studio Logcat utility.
**Testing**:  
Create a Story Producer directory with the "002 Lost Coin.bloom" file.
Start Story Producer and  Story Producer will parse the  "002 Lost Coin.bloom"  and create the "002 Lost Coin" directory.  
Exit Story Producer and then  corrupt the "002 Lost Coin"/project/story.json file by inserting extraneous '}' characters into the file.  
Start Story Producer and Story Producer will process the corrupt story.json file, send a log message to …

Added exception Handling & log messages for Story to/from Jason

---

app/src/main/java/org/sil/storyproducer/model/Story.kt
app/src/main/java/org/sil/storyproducer/model/StoryIO.kt

**Problem:** The story.jason file is not saved during parse error which causes loss of data
**Solution:** Save the story.jason file to a backup file and add new data fields to the story.jason file that includes a file write timestamp, Story Producer app version name (string)  and Story Producer app version code (integer).
**Test 1:** Create a Story Producer directory with the "002 Lost Coin.bloom" file. Start Story Producer and  Story Producer will parse the  "002 Lost Coin.bloom"  and create the "002 Lost Coin/project" directory.  Exit Story Producer and see if the story.json file in "002 Lost Coin/project" includes the new fields. 
**Expected:** The following new fields are in the story.json file: storyToJasonAppVersionCode, storyToJasonAppVersionName and storyToJasonTimeStamp 
**Test …

Issue #555: Create backup file for exceptions & add fields to story.json

---

app/src/main/java/org/sil/storyproducer/activities/BaseActivity.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/FilterOptions.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/FilterToolbarFrag.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/StoryPageAdapter.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/StoryPageFragment.kt
app/src/main/java/org/sil/storyproducer/controller/storylist/StoryPageTab.kt
app/src/main/java/org/sil/storyproducer/model/Story.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/filter_chip_choice.xml
app/src/main/res/layout/filter_toolbar.xml
app/src/main/res/layout/story_list_container.xml
app/src/main/res/layout/story_list_item.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

**Problem:** For issue #407, "Add filtering to SP's 'Story Templates' List", the pull request #561 was submitted by Cedarville Students. The pull request #561 did not have the latest changes from the sillsdev baseline.
**Solution:** Merge #561 into the latest sillsdev baseline incorporating all the latest sillsdev changes and do nominal checkout of the merged baseline along with functional checkout of the new capabilities.
**Testing Problems:** The following problems were identified and fixed during integration testing checkout:
- Changes in issue 561 turnover broke the registration process. The same fix that was identified in issue 573 (pull Issue #573: SP hangs on Registration Submit #582) was reused. (see SHA1: 19920750e9)
- The 561 pull deleted some network code used in remote …

Sp 407 story filter for baseline 3.0.6

---

README.md

I found a Google Drive link [in a strings.xml file](https://github.com/alexcwatt/StoryProducer/blob/9a3a045bd740436fb9a99424e7be081c273b2617/app/src/main/res/values/strings.xml#L105) that I think is the accurate link.

Fix broken README link to template files on Google Drive

---

app/src/main/res/layout/activity_share.xml
app/src/main/res/layout/exported_video_row.xml

**Problem:**  The geometry for the Share Phase Screen is incorrect causing incorrect scrolling and lines to overlap within a single video name when it wraps to the next line.
**Solution:** Update the geometry of the Share Phase Screen to properly scroll and to properly line wrap.
Before fix:
After fix:

SP550-SharePhase Scrolling Fix

---

app/src/main/java/org/sil/storyproducer/controller/adapter/RecordingsListAdapter.kt
app/src/main/java/org/sil/storyproducer/model/Phase.kt
app/src/main/java/org/sil/storyproducer/tools/file/AudioFiles.kt
app/src/main/res/values/strings.xml

**Per Issue #606:** "Wordlinks quick fix for text back translation #606", this pull request swaps out the place holder text on the Worklinks audio file names & editable text box with the following text:
Replace "WordLinks 1" with "WordLinks 1 -> Press and hold to back translate" on the WordLinks window that contains the audio file name.
Replace "Choose a new name"  with "Type a back translation or spell the name" on the WorkLinks editable text box.
**Testing:**  Changes were tested on the following platforms:
Google Pixel 5 phone running Android 12
Google Pixel 3 emulator running Android 8
Motorola Phone running Android 9.

SP-606 Add help for back Translation

---

app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/res/values/strings.xml

Per Issue #611, update Story Producer to create the Word Links Directory if it does not exist and allow the CSV file that contains the word links data to have a variable name.  This name begins with "wordlinks" and ends with ".csv", e.g.: worklinks-DKH.csv.
Testing:  This fix was successfully tested on an Android 12, Pixel 5 phone and on an Android 8, Pixel 3 Android Studio emulation.

SP 611: Create Word Links directory and allow CSV files to have different names

---

app/src/main/java/org/sil/storyproducer/activities/WelcomeDialogActivity.kt
app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/res/menu/drawer_view.xml
app/src/main/res/values/strings.xml

Per Issue #571, update Story Producer to allow a user to load additional templates from the MainActivity via a URL (which points to a Google shared drive).  This URL is referenced in the "Welcome Screen" and when a user picks a menu option from the MainActivity.  Previously, the URL was embedded in the html for the "Welcome Screen".  To avoid duplication, the URL was moved to the Workspace object where it can be inserted into the "Welcome Screen" html before display or used when the "More Templates"  menu option is selected from the MainActivity.
**Testing:** 
Using an Android Studio debug build, templates were downloaded  from the "Welcome Screen" and the MainActivity via the shared drive URL. Test were run on an Android11 Pixel 5 phone and on an Android 9 Pixel 2 emulator.
Successfully …

SP571-From MainActivity, user can download templates from URL

---

app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/java/org/sil/storyproducer/tools/DrawerItemClickListener.kt
app/src/main/res/values/global_menu_array.xml

Per Issue #571, update Story Producer to allow a user to load additional templates.  Pull #619 allows a user to download additional story templates from the main menu.  This pull request allows a user to download additional story templates from any of the phases.
Testing:
Using an Android Studio debug build, templates were downloaded from the Phase menu via the shared drive URL. Test were run on an Android11 Pixel 5 phone and on an Android 9 Pixel 2 emulator.
Successfully ran Espresso tests on a Pixel 2 Android 9 emulator using the debug build.
New Menu in Phase Activity:

SP571-Added URL template download to Phase menu

---

app/src/main/assets/accuracy_check.html
app/src/main/assets/community_work.html
app/src/main/assets/finalize.html
app/src/main/assets/learn.html
app/src/main/assets/registration.html
app/src/main/assets/share.html
app/src/main/assets/story_list.html
app/src/main/assets/translate_revise.html
app/src/main/assets/voice_studio.html
app/src/main/assets/word_links.html
app/src/main/java/org/sil/storyproducer/controller/RegistrationActivity.kt
app/src/main/java/org/sil/storyproducer/model/Phase.kt
app/src/main/res/layout/activity_registration.xml
app/src/main/res/values/strings.xml

This pull request integrates Cedarville pull 558 into the current base line.  Pull 558 is based on #552 (Registration page - Add Help button & change drawer label).  
#552 Summary:
- add the phase menu bar to the registration activity
- update drawer name to ‘Accuracy Checker Info’
- add registration HTML help doc
This pull request also integrates #590 (Update the Help docs for Registration and Story Templates).  Per #590 all the html documents were updated to include the newest phase names and exclude references to ROCC.
Testing:
Using an Android Studio debug build, registration help menu bar was tested.  The following html help documents were reviewed and displayed: 
- accuracy_check.html
- community_work.html
- finalize.html
- learn.html
- registration.html
- share.html
- …

SP590, SP552, Pull 558:  Add registration help and update help html documents

---

app/src/main/java/org/sil/storyproducer/model/Phase.kt

Per SP596, review Crashlytics reports for high frequency fatal exceptions.  This pull fixes  a coding error in Phase.kt::checkValidDisplaySlideNum in which the slide index number was not checked for validity before use.
Testing:
I was unable to find the test scenario that caused this crash, so, I walked through the code with the debugger forcing an illegal index to be passed into  checkValidDisplaySlideNum.  checkValidDisplaySlideNum did not crash but returned the correct response.
Test were run on an Android12 Pixel 5 phone and on an Android 9 Pixel 2 emulator.

SP596-Fix for checkValidDisplaySlideNum illegal index

---

app/src/main/assets/wordlinks.csv
app/src/main/java/org/sil/storyproducer/model/Workspace.kt
app/src/main/res/values/strings.xml

As outlined in issue #622, for SP v3.1 there should be no default wordlist file installed automatically. 
Users will need to download and install on their phone the Wordlinks file appropriate for the LWC of their templates

SP-622 Fix for 'no default wordlist file'

---

app/src/main/res/values/strings.xml

This removes, for now, the UI labels for the wordlinks fields that v3.1 does not show.

Clean up wordlinks view for v3.1

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Got this working in Android Studio 2021.1.1
Needed to do this: in Settings - Build Tools - Gradle selected JDK ver 11
I tested debug app in Pixel 2 API 28 emulator.
[@DaleHensley](https://github.com/DaleHensley) if you approve this PR, in the github pull request, please go to the Files Changed tab and use the green Review Changes button to comment or approve etc.

upgrading gradle to 7.1.2, AS 2021.1.1, JDK 11

---

app/src/main/java/org/sil/storyproducer/tools/Utilities.kt
app/src/main/java/org/sil/storyproducer/tools/media/pipe/PipedMediaCodec.kt

Per issue #630, update software to proper keep audio and slides in sync.
During Android 12 testing, the encoding of the audio to the slides was out of sync, ie,
the slide video finished earlier than the audio track.  This produced a video with the
audio being played over the wrong slide.
The origin code assumed the encoder for a codec mime type (eg, "video/avc") would always
properly encode the video.  As it turns out, there can be more than one encoder for
a mime type, so, picking the first encoder in the list may not produce the desired
video.  The code was updated to look for a codec encoder with a specific canonical name that
has always worked for us in the past. 
1. Load a clean version of "002 Lost Coin.bloom" into the device.
2. Execute Story Producer app and "002 Lost Coin" should …

SP630 audio video out of sync4 android12

---

app/src/main/java/org/sil/storyproducer/controller/export/FinalizeActivity.kt

Per SP637, Allow subtitle text during videos with movement. 
With the implementation of SP456 (Add grey rectangle to backdrop text "sub titles"), the text sub titles are now readable during picture movement.  Remove the restriction that would not allow text sub titles to be displayed during picture movement.
Tested on Pixel 5 Android 12
Here is an example:
https://user-images.githubusercontent.com/78509270/161406165-1df4a1e6-0641-4ad7-b16d-e78df4c530d1.mp4
For Android 11 releases and later, some Codec encoders have a problem encoding a video with NO picture movement (see Issue #630, fix pull #634).  As tested to date, all Codec encoders are able to process a picture with movement.  With this fix, the user will always be able to display subtitles by using a picture with movement.

SP637: Allow subtitle text during videos with movement (KB Effect)

---

app/src/main/java/org/sil/storyproducer/model/Workspace.kt

Per Issue #625, clear word links data from memory when selecting a new SP workspace.  
Recreate error as described in #625 and updated software to delete all Wordlinks terms & search trees when switching to a new SP workspace.
This was tested the following devices:
Pixel 5 Android 12
Samsung Android 9

SP625-When selecting new work space, clear Wordlinks data from memory

---

app/src/main/java/org/sil/storyproducer/controller/MainActivity.kt
app/src/main/java/org/sil/storyproducer/controller/SelectTemplatesFolderController.kt
app/src/main/res/values/strings.xml

Auto install the 'demo' story if 'SP Templates' folder is empty. 
Whenever story list is short, display a snack-bar message on how the user can download story templates from Bloom Library.
Check download stories message, each time the Main Activity is shown + prevent duplicate demo story

Auto-install demo, prompt BL download

---

app/src/main/java/org/sil/storyproducer/tools/file/FileIO.kt

This reverts commit 2a6b0ebf926cefb53ba1e7da79a72a8873433a86. 
Peter found that this fix was slowing down the import of bloomSource templates.

Revert "Migrating automatic storage - Bug fix on SG-S7"

---

app/src/test/java/org/sil/storyproducer/test/model/TestParsePhotoStory.kt

@bryanwussow This should resolve the issue you mentioned. There are a few things here:
1. We can't use the mocks the way we had before, due to changes in the parsing. I think it's actually cleaner to not be using them anymore.
2. I had to change the assertion from `5` to `4`. I don't know why there is this discrepancy, perhaps it can be dug into further but when I had tried running these tests months ago, I'd noticed this issue then also. It might make sense to just take this change.
3. There is a test that I deleted that I don't think is useful. I could double check later if there is another way to accomplish the spirit of the test, but for now I've removed it.

Stop using mock for storyPath in TestParsePhotoStory, make tests pass
